### ISSUE TITLE
Fix how MRISwrite() resolves full path names

### ISSUE THREAD

**Issue by pwighton** [corticometrics/freesurfer#1]
All utilities that write surfaces call MRISwrite().  If the full path isn't specified, it resolves to the directory the input surface originated from.  To be POSIX compliant, it should resolve to the current working directory (cwd)

Example:

Start with the following initial filesystem

```
.
|-- indir
|   `-- rh.smoothwm.nofix
`-- outdir
```

now cd into `outdir` and run:

```
mris_inflate ../indir/rh.smoothwm.nofix lh.inflated.nofix
```

This results in the following filesystem:

```
.
|-- indir
|   |-- lh.inflated.nofix
|   `-- rh.smoothwm.nofix
`-- outdir
    `-- rh.sulc
```

And to be POSIX compliant, we want:

```
.
|-- indir
|   `-- rh.smoothwm.nofix
`-- outdir
|   |-- lh.inflated.nofix
    `-- rh.sulc
```

**Comment by SangHLee** [comment]
This is as test demo issue. Hence, it is closed
